//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP01._01_Nechaeva.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisment
    {
        public int Id { get; set; }
        public string AdDescription { get; set; }
        public int City { get; set; }
        public System.DateTime AdDate { get; set; }
        public string Photo { get; set; }
        public int Category { get; set; }
        public int AdOwner { get; set; }
        public string AdName { get; set; }
    
        public virtual Category Category1 { get; set; }
        public virtual City City1 { get; set; }
        public virtual Users Users { get; set; }
    }
}
